import { defineConfig } from 'tsdown'

/**
 * Build runtime JS for the dsh-ragflow plugin. Type declarations are not
 * generated by tsdown (vendor .d.ts files are not standard ES module exports
 * and rolldown cannot resolve them); the DSH source-launch path loads
 * TypeScript directly through tsx when lib/ is absent.
 */
export default defineConfig({
  entry: ['src/index.ts', 'src/invariant.ts'],
  outDir: 'lib',
  format: 'esm',
  fixedExtension: false,
  dts: false,
  clean: true,
  deps: {
    neverBundle: [
      '@deepseek-ai/cordis',
      '@deepseek-ai/schemastery',
      '@deepseek-ai/dsh-credentials',
      '@deepseek-ai/dsh-invariants',
      '@deepseek-ai/dsh-launch-environment',
      '@deepseek-ai/dsh-llm',
      '@deepseek-ai/dsh-system-prompt',
      '@deepseek-ai/dsh-tools',
    ],
  },
})
